# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" , "develop"]
    paths-ignore:
      - "README.md"
      - "CHANGELOG.md"
  pull_request:
    branches: [ "main" , "develop" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: pkg build
        working-directory: ./internal/pkg
        run: go build -v ./...

      - name: identity_service build
        working-directory: ./internal/services/identity_service
        run: go build -v ./...

      - name: basket_service build
        working-directory: ./internal/services/basket_service
        run: go build -v ./...

      - name: delivery_service build
        working-directory: ./internal/services/delivery_service
        run: go build -v ./...

      - name: basket_service test
        working-directory: ./internal/services/basket_service
        run: go test -v ./...

      - name: identity_service test
        working-directory: ./internal/services/identity_service
        run: go test -v ./...

      - name: delivery_service test
        working-directory: ./internal/services/delivery_service
        run: go test -v ./...
